<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>output/$(AssemblyName)/</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="pwsh -Command &quot;New-BinaryModuleManifest -Path $(TargetDir)$(TargetName).psd1 -ModulePath $(ProjectDir) -Guid 65066b67-10ed-44c8-b270-a8c9a7054cb7 -Verbose&quot;" />
    </Target>
</Project>
